name: 'PR Tasks Check'
on: 
  pull_request:
    types: [opened, edited]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: codykaup/task-completed-checker-action@update-check
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
